apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storage-mongo
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Retain
parameters:
  kind: Managed
  storageaccounttype: StandardSSD_LRS
